### PR TITLE
add codecov

### PR DESCRIPTION
**Pull request by steven2249**
I am an rOpensci intern, working on adding test coverage components.

### CODE REVIEW

**Comment by sckott** [comment]
@SaraVarela any thoughts here?

**Comment by SaraVarela** [comment]
Hi @steven2249 and @sckott. @steven2249 please, feel free to merge all the small improvements that you want! many thanks for the help! :-)

**Comment by sckott** [comment]
@SaraVarela you are the maintainer - so I'd prefer you press the button, but happy to do so with these small things if you say so

**Comment by javigzz** [comment]
Hi @steven2249 I see there is a conflict to merge. Your branch does not include the last commit in master by @sckott. Is this intentional and we should discard the changes in https://github.com/ropensci/paleobioDB/commit/1dc2099b0b01c385a9f4f6f223c7654ddd7ed71d 
or can we add those two lines to the current "language R" version of .travis.yml?

**Comment by javigzz** [comment]
closing PR after fixing conflicts in favor of https://github.com/ropensci/paleobioDB/pull/37

**Pull request closed without merging**
